# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stubs/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10stubs/auth.proto\x12\x04\x61uth\"W\n\x07\x41\x64\x64ress\x12\x13\n\x06street\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x1e\n\x07\x63ountry\x18\x03 \x01(\x0e\x32\r.auth.CountryB\t\n\x07_street\"\x94\x01\n\x04User\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12#\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32\r.auth.AddressH\x02\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_nameB\n\n\x08_address\"\x1d\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"+\n\x0fRegisterRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User\"9\n\x0fGetUsersRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\"B\n\x10GetUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.auth.User\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05*M\n\x07\x43ountry\x12\x0b\n\x07UKRAINE\x10\x00\x12\x07\n\x03USA\x10\x01\x12\x06\n\x02UK\x10\x02\x12\n\n\x06POLAND\x10\x03\x12\t\n\x05JAPAN\x10\x04\x12\r\n\tAUSTRALIA\x10\x05\x32\xa6\x01\n\x0b\x41uthService\x12)\n\x05Login\x12\x12.auth.LoginRequest\x1a\n.auth.User\"\x00\x12/\n\x08Register\x12\x15.auth.RegisterRequest\x1a\n.auth.User\"\x00\x12;\n\x08GetUsers\x12\x15.auth.GetUsersRequest\x1a\x16.auth.GetUsersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stubs.auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COUNTRY']._serialized_start=469
  _globals['_COUNTRY']._serialized_end=546
  _globals['_ADDRESS']._serialized_start=26
  _globals['_ADDRESS']._serialized_end=113
  _globals['_USER']._serialized_start=116
  _globals['_USER']._serialized_end=264
  _globals['_LOGINREQUEST']._serialized_start=266
  _globals['_LOGINREQUEST']._serialized_end=295
  _globals['_REGISTERREQUEST']._serialized_start=297
  _globals['_REGISTERREQUEST']._serialized_end=340
  _globals['_GETUSERSREQUEST']._serialized_start=342
  _globals['_GETUSERSREQUEST']._serialized_end=399
  _globals['_GETUSERSRESPONSE']._serialized_start=401
  _globals['_GETUSERSRESPONSE']._serialized_end=467
  _globals['_AUTHSERVICE']._serialized_start=549
  _globals['_AUTHSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
