# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stubs import auth_pb2 as stubs_dot_auth__pb2


class AuthServiceStub(object):
    """Auth service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/auth.AuthService/Login',
                request_serializer=stubs_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=stubs_dot_auth__pb2.User.FromString,
                )
        self.Register = channel.unary_unary(
                '/auth.AuthService/Register',
                request_serializer=stubs_dot_auth__pb2.RegisterRequest.SerializeToString,
                response_deserializer=stubs_dot_auth__pb2.User.FromString,
                )
        self.GetUsers = channel.unary_unary(
                '/auth.AuthService/GetUsers',
                request_serializer=stubs_dot_auth__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=stubs_dot_auth__pb2.GetUsersResponse.FromString,
                )


class AuthServiceServicer(object):
    """Auth service definition
    """

    def Login(self, request, context):
        """Login User with email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Register User with User object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Get page of Users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=stubs_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=stubs_dot_auth__pb2.User.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=stubs_dot_auth__pb2.RegisterRequest.FromString,
                    response_serializer=stubs_dot_auth__pb2.User.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=stubs_dot_auth__pb2.GetUsersRequest.FromString,
                    response_serializer=stubs_dot_auth__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Auth service definition
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Login',
            stubs_dot_auth__pb2.LoginRequest.SerializeToString,
            stubs_dot_auth__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/Register',
            stubs_dot_auth__pb2.RegisterRequest.SerializeToString,
            stubs_dot_auth__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GetUsers',
            stubs_dot_auth__pb2.GetUsersRequest.SerializeToString,
            stubs_dot_auth__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
