"""Initial

Revision ID: 3aa6d94ee7e3
Revises: 
Create Date: 2023-08-30 20:27:10.850966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa6d94ee7e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('country', sa.Enum('UKRAINE', 'USA', 'UK', 'POLAND', 'JAPAN', 'AUSTRALIA', name='country'), nullable=False),
    sa.PrimaryKeyConstraint('street', 'city', 'country')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('address_city', sa.String(length=255), nullable=False),
    sa.Column('address_country', sa.Enum('UKRAINE', 'USA', 'UK', 'POLAND', 'JAPAN', 'AUSTRALIA', name='country'), nullable=False),
    sa.ForeignKeyConstraint(['address_street', 'address_city', 'address_country'], ['addresses.street', 'addresses.city', 'addresses.country'], ),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('addresses')
    # ### end Alembic commands ###
